### ISSUE TITLE
Level Lock Plugin Bug

### ISSUE THREAD

**Issue by JustXray** [ObliqueNET/Stratos#143] opened 2019-03-29 02:34 UTC
So I have ran into this problem more than once and so have my friends. Basically I will level lock a mon and when I reach the level I locked it at, it will overlevel. This is an issue because I level locked my mon for the ground gym and it overleveled by one. I would like to see this issue fixed and I would also like to ask that the mon be de-leveled by 1 level.

Thanks!

**Comment by Forensiic** [comment] 2019-04-01 04:15
After a number of attempts, we have been unsuccessful in reproducing an error with the plugin. To be more specific, we haven't seen a pokemon over level after being locked. If you could provide any extra details on the issue, it would be appreciated.

**Comment by JustXray** [comment] 2019-04-01 04:19
It may be a glitch when the mon gets switched out in a PC but what usually happens/has happened to me is that I will level lock my pokemon then power level them to the level I want them to be at. Once they are at the level I usually check them to make sure they have leveling disabled. In the instance the other day the mon over-leveled after being level locked and I went to check its leveling status and it was enabled.

**Comment by Forensiic** [comment] 2019-04-01 04:34
The in-game disable leveling button and the level lock plugin are two separate entities, they are not connected. You can't control the level lock system with the in-game disable leveling button. Additionally, you can't control the in-game disable leveling button with the level locking commands. You can use one or the other, not both. The level lock plugin has been designed (and tested) to disable leveling the moment the pokemon reaches the specified locked level, regardless of the EXP source. It does not care about any additional exp gained from the battle or a rare candy - from our skills plugin. With that being said, if you can provide any proof of the plugin not working as intended; screenshots, videos, etc it would greatly increase the chances of any possible bugs being found/fixed.

**Comment by JustXray** [comment] 2019-04-01 04:58
I know how the plugin works. I am saying that sometimes it does not stop leveling when the level is reached but instead does not disable leveling. I will try to capture evidence the next time I am leveling my pokemon.

**Comment by fatyg5** [comment] 2019-04-18 03:58
Closing due to lack of evidence.

**Closed by fatyg5** 2019-04-18 03:58 UTC
